export interface Champion {
  name: string;
  city: string;
  state: string;
  lat: number;
  lng: number;
  website?: string;
}

export const champions: Champion[] = [
  {
    name: "Presidio Bitcoin",
    city: "San Francisco",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    website: "https://www.presidiobitcoin.org/",
  },
  {
    name: "Denver Space",
    city: "Denver",
    state: "CO",
    lat: 39.7392,
    lng: -104.9903,
    website: "https://denver.space/",
  },
  {
    name: "The Park, Nashville",
    city: "Nashville",
    state: "TN",
    lat: 36.1627,
    lng: -86.7816,
    website: "https://www.meetup.com/bitcoinpark/",
  },
  {
    name: "ATL BitLab",
    city: "Atlanta",
    state: "GA",
    lat: 33.749,
    lng: -84.388,
    website: "https://atlbitlab.com/",
  },
  {
    name: "The Park, Austin",
    city: "Austin",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    website: "https://www.meetup.com/bitcoin-park-austin/",
  },
  {
    name: "Adam",
    city: "De Soto",
    state: "KS",
    lat: 38.9797,
    lng: -94.968,
    website: "https://kcbitcoiners.com/",
  },
  {
    name: "Coinward",
    city: "Miami",
    state: "FL",
    lat: 25.7617,
    lng: -80.1918,
    website: "https://btcgrove.com/",
  },
  {
    name: "Trey",
    city: "Washington",
    state: "DC",
    lat: 38.9072,
    lng: -77.0369,
    website: "https://bitcoindistrictinitiative.org/",
  },
  {
    name: "Andrew",
    city: "Charlotte",
    state: "NC",
    lat: 35.2271,
    lng: -80.8431,
    website: "https://www.meetup.com/bitcoincharlotte/",
  },
  {
    name: "Douglas",
    city: "Indianapolis",
    state: "IN",
    lat: 39.7684,
    lng: -86.1581,
    website: "https://indybitcoinmeetup.com/",
  },
  {
    name: "Austin",
    city: "Seattle",
    state: "WA",
    lat: 47.6062,
    lng: -122.3321,
    website: "https://x.com/austinvach",
  },
  {
    name: "Joseph",
    city: "Ann Arbor",
    state: "MI",
    lat: 42.2808,
    lng: -83.743,
    website: "https://www.mibtc.org/",
  },
  {
    name: "Andrew",
    city: "North Kingstown",
    state: "RI",
    lat: 41.5501,
    lng: -71.4562,
    website: "https://x.com/ribitcoiners",
  },
  {
    name: "Chris",
    city: "Los Angeles",
    state: "CA",
    lat: 34.0522,
    lng: -118.2437,
    website: "https://x.com/_chrishwang",
  },
  {
    name: "Tom",
    city: "Boston",
    state: "MA",
    lat: 42.3601,
    lng: -71.0589,
    website: "https://x.com/bostonbitdevs",
  },
  {
    name: "Phil",
    city: "Concord",
    state: "NH",
    lat: 43.2081,
    lng: -71.5376,
    website: "https://www.meetup.com/massachusetts-bitcoin-meetup/",
  },
  {
    name: "Evan",
    city: "Lincoln",
    state: "NE",
    lat: 40.8136,
    lng: -96.7026,
    website: "https://primal.net/Nebraska",
  },
  {
    name: "Justin",
    city: "Minneapolis",
    state: "MN",
    lat: 44.9778,
    lng: -93.265,
    website: "https://x.com/m1sterc001guy",
  },
  {
    name: "mnpezz",
    city: "New Orleans",
    state: "LA",
    lat: 29.9511,
    lng: -90.0715,
    website: "https://x.com/mnpezz",
  },
  {
    name: "Jason",
    city: "Round Rock",
    state: "TX",
    lat: 30.5083,
    lng: -97.6789,
    website: "https://roundrockbitcoiners.com/",
  },
];
